### ISSUE TITLE
VoteStatusButtons struggle to load when multiple instances are connected

### ISSUE THREAD

**Issue by jex441** [turbo-src/turbo-src#116]
This appears to be most apparent with new pull requests, which rely on a GitHub API call to get its data.

Some optimization could help load them more reliably.

**Comment by 7db9a** [comment]
We think the culprit is excessive processing on the instance (aka back-end) that results in extensions request timing out when getting info on the PR. We strongly suspect, but haven't confirmed.
 
We only need to optimize until we can have a reasonable number of users connected to Turbosrc, but here is working list of biggest time killers that could potentially be optimized

1. Service must make a request to Github to get pull request info (such as if it's open, closed, or merged) on each load.
2. Console logs.
3. Unreliable connection from the instance to the client results in excessive or failed socket re-connection attempts.
4 . ...

**Comment by 7db9a** [comment]
@jex441 fast turnaround! I see actions tests failed. Let me know if you need a second set of eyes.

**Comment by 7db9a** [comment]
Fixed and already pushed to master
